# Generated by Django 3.1.7 on 2022-01-16 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='название блока задач')),
            ],
            options={
                'verbose_name': 'блок задач',
                'verbose_name_plural': 'блоки задач',
            },
        ),
        migrations.CreateModel(
            name='Executer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ответственный исполнитель')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=250, verbose_name='задача')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spravka.block', verbose_name='блок')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='дата подзадачи')),
                ('update', models.DateField(auto_now=True)),
                ('content', models.TextField(verbose_name='содержание подзадачи')),
                ('deadline', models.DateField(blank=True, verbose_name='контрольный срок')),
                ('task_cost', models.PositiveSmallIntegerField(verbose_name='с')),
                ('executer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spravka.executer', verbose_name='ответственный исполнитель')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spravka.task')),
            ],
            options={
                'verbose_name': 'подзадача',
                'verbose_name_plural': 'подзадачи',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='что изменилось')),
                ('update_progress', models.DateField(auto_now=True, verbose_name='дата обновления')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spravka.subtask', verbose_name='прогресс')),
            ],
            options={
                'verbose_name': 'прогресс',
                'verbose_name_plural': 'прогресс',
            },
        ),
    ]
